[versions]
kotlin = "1.6.21"
coroutines = "1.6.1"

android-gradle = "7.1.2"
androidx-core = "1.7.0"
androidx-lifecycle = "2.4.1"
androidx-activity = "1.4.0"
androidx-preference = "1.2.0"
androidx-navigation = "2.4.2"

compose = "1.2.0-beta02"
material = "1.6.1"
material3 = "1.0.0-alpha12"
dagger = "2.41"
coil = "2.1.0"

accompanist = "0.24.9-beta"
secrets-gradle-plugin = "2.0.1"

okhttp = "4.9.3"
retrofit = "2.9.0"

kakao = "2.9.1"

mockk = "1.12.0"
junit = "4.13.2"
junit5 = "5.7.2"

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android.gradle" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }

androidx-compose-ui-core = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-tooling-core = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-customview-poolingcontainer = { module = "androidx.customview:customview-poolingcontainer", version = "1.0.0-beta01" }

androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }

google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
google-accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
google-secrets-gradle = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secrets-gradle-plugin" }

material = { module = "com.google.android.material:material", version.ref = "material" }
spectrum = "com.facebook.spectrum:spectrum-default:1.3.0"

javax-inject = "javax.inject:javax.inject:1"

google-services = "com.google.gms:google-services:4.3.12"

# Network
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

gson = "com.google.code.gson:gson:2.9.0"

# Kakao
kakao-user = { module = "com.kakao.sdk:v2-user", version.ref = "kakao" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

# Test
junit4 = { module = "junit:junit", version.ref = "junit" }
junit5-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit5-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }

truth = "com.google.truth:truth:1.1.3"
mockk-core = { module = "io.mockk:mockk", version.ref = "mockk" }

hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "dagger" }
hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }

[bundles]
junit5 = ["junit5-jupiter-api", "junit5-jupiter-params", "junit5-jupiter-engine", "junit5-vintage-engine"]
